In [1]:
import pandas as pd
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
from sklearn.model_selection import StratifiedKFold
import numpy as np
from sklearn.linear_model import LogisticRegression
import pickle
from sklearn.pipeline import Pipeline
from imblearn.under_sampling import ClusterCentroids
from sklearn.svm import SVC

In [2]:
X_train = pd.read_csv('without_PCA/X_train.csv')
x_test = pd.read_csv('without_PCA/X_test.csv')
y_train = pd.read_csv('without_PCA/Y_train.csv')
y_test = pd.read_csv('without_PCA/Y_test.csv')

In [3]:
from sklearn.cluster import MiniBatchKMeans

In [4]:
cc = ClusterCentroids(estimator=MiniBatchKMeans())
X_res, y_res = cc.fit_resample(X_train, y_train)

C:\Users\nagar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\nagar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1902: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 3072 or by setting the environment variable OMP_NUM_THREADS=4
  warnings.warn(


In [5]:
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_res, y_res)

C:\Users\nagar\AppData\Local\Temp\ipykernel_4532\2181567766.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X_res, y_res)


RandomForestClassifier()

In [6]:
y_pred = rfc.predict(x_test)

In [7]:
accuracy_score(y_test, y_pred)

0.8681434599156118

In [8]:
f1_score(y_test, y_pred)

0.8339973439575032

In [9]:
confusion_matrix(y_test, y_pred)

array([[1018,  192],
       [  58,  628]], dtype=int64)

In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.84      0.89      1210
           1       0.77      0.92      0.83       686

    accuracy                           0.87      1896
   macro avg       0.86      0.88      0.86      1896
weighted avg       0.88      0.87      0.87      1896



In [12]:
bgc = BaggingClassifier()
bgc.fit(X_res, y_res)

C:\Users\nagar\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier()

In [13]:
y_pred = bgc.predict(x_test)

In [14]:
accuracy_score(y_test, y_pred)

0.8586497890295358

In [15]:
f1_score(y_test, y_pred)

0.82109479305741

In [16]:
confusion_matrix(y_test, y_pred)

array([[1013,  197],
       [  71,  615]], dtype=int64)

In [17]:
print(classification_report(X_res, y_res))

              precision    recall  f1-score   support

           0       0.93      0.84      0.88      1210
           1       0.76      0.90      0.82       686

    accuracy                           0.86      1896
   macro avg       0.85      0.87      0.85      1896
weighted avg       0.87      0.86      0.86      1896



In [26]:
bgc_lr = BaggingClassifier(estimator=LogisticRegression())
bgc_lr.fit(X_res, y_res)

C:\Users\nagar\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(estimator=LogisticRegression())

In [27]:
y_pred = bgc_lr.predict(x_test)

In [28]:
accuracy_score(y_test, y_pred)

0.7974683544303798

In [29]:
f1_score(y_test, y_pred)

0.7632552404438964

In [30]:
confusion_matrix(y_test, y_pred)

array([[893, 317],
       [ 67, 619]], dtype=int64)

In [21]:
bgc_svm = BaggingClassifier(estimator=SVC())

In [22]:
bgc_svm.fit(X_res, y_res)

C:\Users\nagar\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(estimator=SVC())

In [23]:
y_pred = bgc_svm.predict(x_test)

In [25]:
y_pred

array([0, 1, 1, ..., 0, 0, 1], dtype=int64)

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.76      0.84      1210
           1       0.69      0.93      0.79       686

    accuracy                           0.82      1896
   macro avg       0.82      0.84      0.82      1896
weighted avg       0.85      0.82      0.82      1896



In [27]:
confusion_matrix(y_test, y_pred)

array([[917, 293],
       [ 48, 638]], dtype=int64)